### ISSUE TITLE
Working on option for PNG drawings - Autocrop Content

### ISSUE THREAD

**Issue by gabrielrueda** [gabrielrueda/obsidian-xournal-integration-plugin#2]
- Was able to obtain bytes to determine the boundaries of the image - would like more testing for this feature
- Able to crop using Linux command - temporary solution - probably should use node js library or try to crop using the bytes decoding and encoding that I have already been working on 

#### TODO:
 - [ ] Differentiate between PNG and PDF xopp files 
 - [ ] Create hotkey to create png drawing on obsidian - have setting to either auto open or not
 - [ ] When right click image on md file that has an associated xopp -> have option to open in xournal
 - [ ] Integrate autocropping features and ensure xournal exports as png after editing the xournal file

**Comment by gabrielrueda** [comment]
Did not finish due to render content feature replacing it
