### ISSUE TITLE
Release v1.0 to Obsidian Plugin Repository

### ISSUE THREAD

**Issue by gabrielrueda** [gabrielrueda/obsidian-xournal-integration-plugin#3]
#### TODO:
- [x] Check if plugin runs on MacOS
- [x] Ensure plugin meets Obsidian plugin guidelines
- [x] Test Functionality on Linux machine
- [ ] Setup Github Workflow to autobuild from Node.js to Github Release
- [x] Get Plugin working for Flatpak version of Obsidian

#### TODO PT 2 (Can still release without the feature)
- [ ] Render inside obsidian (convert xournal format to SVG) instead of using PDF for preview

Please feel free to add any improvements that can be made below.

**Comment by AnthonyMichaelTDM** [comment]
can confirm that it works on my linux system

**Comment by mi-skam** [comment]
@gabrielrueda I'd like to help too :)

I'll start with the macOS part. I'm running a M1 Pro Macbook (macOS Sonoma 14.4).

Installation was super easy. 

```shell
gh repo clone gabrielrueda/obsidian-xournal-integration-plugin
npm i && npm run build
```

and copied the whole folder to my obsidian's plugin dir.

<img width="792" alt="grafik" src="https://github.com/gabrielrueda/obsidian-xournal-integration-plugin/assets/40042054/bafae6a7-6ed4-4f39-acd8-1b7adac68298">

and it's running 👍 

<img width="695" alt="grafik" src="https://github.com/gabrielrueda/obsidian-xournal-integration-plugin/assets/40042054/15fec0b7-3ef0-4e8a-a22e-bb99365ecefa">

There seems to be a bug though, that I cannot open `*.xopp` files by double-clicking them in a finder, which kind of defeats the whole workflow I guess, but this is up to Xournal on macOS right?

<img width="257" alt="grafik" src="https://github.com/gabrielrueda/obsidian-xournal-integration-plugin/assets/40042054/567ab348-7224-4040-bd43-21130e29cce3">

**Comment by mi-skam** [comment]
Funny, I created a little wrapper (which is in `$PATH`) , which allows to open files passed as arguments, but still it's not working with this extension

`~/.local/bin/xournalpp`:

```shell
#!/bin/bash

BASEDIR="/Applications/Xournal++.app/Contents/MacOS"
cd "$BASEDIR" || exit

./xournalpp "$@"
```

**Comment by gabrielrueda** [comment]
@mi-skam 

Thanks for testing on mac os. I think we can add a feature to our plugin that will force it to open in xournal when we double click. I'll look into this feature and let you know if I find something.
